/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_winjay_practice_so_SOActivity */

#ifndef _Included_com_winjay_practice_so_SOActivity
#define _Included_com_winjay_practice_so_SOActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_winjay_practice_so_SOActivity
 * Method:    num
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_winjay_practice_so_SOActivity_num
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
