/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_winjay_practice_jni_JniTestActivity */

#ifndef _Included_com_winjay_practice_jni_JniTestActivity
#define _Included_com_winjay_practice_jni_JniTestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_winjay_practice_jni_JniTestActivity
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_winjay_practice_jni_JniTestActivity_get
  (JNIEnv *, jobject);

/*
 * Class:     com_winjay_practice_jni_JniTestActivity
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_winjay_practice_jni_JniTestActivity_set
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
